---
services:
  api:
    image: jhumanj/opnform-api:latest
    environment:
      DB_HOST: db
      REDIS_HOST: redis

      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      LOG_CHANNEL: ${LOG_CHANNEL:-errorlog}
    env_file: ./.env
    volumes:
      - laravel-persist:/persist

  ui:
    image: jhumanj/opnform-ui:latest
    environment:
      APP_URL: ${APP_URL:-http://localhost}
      NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL:-${APP_URL:-/}}
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-$APP_URL/api}
      NUXT_PRIVATE_API_BASE: http://ingress/api
    env_file: ./client/.env
    volumes:
      - ./client:/app


  redis:
    image: redis:latest

  minio:
    image: minio/minio:latest

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE:-forge}
      POSTGRES_USER: ${DB_USERNAME:-forge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-forge}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ingress:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80

volumes:
  laravel-persist:
  postgres-data:
  minio-storage:
